@startuml lab2
left to right direction

actor Admin
actor Customer
actor "Payment service" as PaymentService

usecase "Authorization" as Auth
usecase "Reset Password" as RP

usecase "Manage categories" as MC
usecase "Manage Products" as MP

usecase "Generate sales report" as GSR

usecase "Browse Products" as BP
usecase "View products details" as VPD

usecase "Add to order" as ATC
usecase "Place order" as PO
usecase "Make payment" as MPAY
usecase "Apply discount" as AD

usecase "View orders" as VO
usecase "Update order Status" as UOS
usecase "Track order status" as TOS

Admin --|> Customer
Admin --> Auth
Customer --> Auth
Customer --> RP
Admin --> MC
Admin --> MP
Admin --> GSR

Customer --> BP
Customer --> ATC
Customer --> VO

PaymentService --> MPAY

BP <|-- VPD : "Extends"

PO ..> MPAY : "Use"
PO <|-- AD : "Extends"
PO <.. ATC : "Use"

VO <.. UOS : "Use"
VO <.. TOS : "Use"

@enduml
